version: "3.8"

services:
  redis-master:
    image: redis:7-alpine
    container_name: ecommerce-redis-master
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6379:6379"
    volumes:
      - redis_master_data:/data
    networks:
      - ecommerce-network
    restart: unless-stopped

  redis-replica-1:
    image: redis:7-alpine
    container_name: ecommerce-redis-replica-1
    command: redis-server --replicaof redis-master 6379 --replica-read-only yes
    depends_on:
      - redis-master
    volumes:
      - redis_replica1_data:/data
    networks:
      - ecommerce-network
    restart: unless-stopped

  redis-replica-2:
    image: redis:7-alpine
    container_name: ecommerce-redis-replica-2
    command: redis-server --replicaof redis-master 6379 --replica-read-only yes
    depends_on:
      - redis-master
    volumes:
      - redis_replica2_data:/data
    networks:
      - ecommerce-network
    restart: unless-stopped

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: ecommerce-redis-sentinel-1
    command: >
      sh -c "echo 'sentinel monitor mymaster redis-master 6379 2
             sentinel down-after-milliseconds mymaster 5000
             sentinel parallel-syncs mymaster 1
             sentinel failover-timeout mymaster 10000' > /tmp/sentinel.conf &&
             redis-sentinel /tmp/sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - ecommerce-network
    restart: unless-stopped

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: ecommerce-redis-sentinel-2
    command: >
      sh -c "echo 'sentinel monitor mymaster redis-master 6379 2
             sentinel down-after-milliseconds mymaster 5000
             sentinel parallel-syncs mymaster 1
             sentinel failover-timeout mymaster 10000' > /tmp/sentinel.conf &&
             redis-sentinel /tmp/sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - ecommerce-network
    restart: unless-stopped

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: ecommerce-redis-sentinel-3
    command: >
      sh -c "echo 'sentinel monitor mymaster redis-master 6379 2
             sentinel down-after-milliseconds mymaster 5000
             sentinel parallel-syncs mymaster 1
             sentinel failover-timeout mymaster 10000' > /tmp/sentinel.conf &&
             redis-sentinel /tmp/sentinel.conf"
    depends_on:
      - redis-master
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  redis_master_data:
  redis_replica1_data:
  redis_replica2_data:

networks:
  ecommerce-network:
    external: true
