# docker-compose.services.yaml

services:
   # Dịch vụ Migration
   migration-service:
      build:
         context: .
         dockerfile: ./docker/migration-service/Dockerfile
      container_name: ecommerce_migration_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
      restart: "no"

   # User Service
   user-service:
      build:
         context: .
         dockerfile: ./cmd/user-service/Dockerfile
      container_name: ecommerce_user_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_USER: 50051
         METRICS_PORT_USER: 9101
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50051:50051"
         - "9101:9101"
      depends_on:
         migration-service:
            condition: service_completed_successfully
      restart: always

   # Product Service
   product-service:
      build:
         context: .
         dockerfile: ./cmd/product-service/Dockerfile
      container_name: ecommerce_product_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_PRODUCT: 50052
         METRICS_PORT_PRODUCT: 9102
         KAFKA_BROKER_ADDR: kafka:9092
         KAFKA_PRODUCT_EVENTS_TOPIC: product_events
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50052:50052"
         - "9102:9102"
      depends_on:
         migration-service:
            condition: service_completed_successfully
      restart: always

   # Order Service
   order-service:
      build:
         context: .
         dockerfile: ./cmd/order-service/Dockerfile
      container_name: ecommerce_order_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_ORDER: 50053
         METRICS_PORT_ORDER: 9103
         PRODUCT_GRPC_ADDR: product-service:50052
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50053:50053"
         - "9103:9103"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         product-service:
            condition: service_started
      restart: always

   # Cart Service
   cart-service:
      build:
         context: .
         dockerfile: ./cmd/cart-service/Dockerfile
      container_name: ecommerce_cart_service
      environment:
         REDIS_ADDR: redis:6379
         GRPC_PORT_CART: 50054
         METRICS_PORT_CART: 9104
         PRODUCT_GRPC_ADDR: product-service:50052
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50054:50054"
         - "9104:9104"
      depends_on:
         product-service:
            condition: service_started
      restart: always

   # Payment Service
   payment-service:
      build:
         context: .
         dockerfile: ./cmd/payment-service/Dockerfile
      container_name: ecommerce_payment_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_PAYMENT: 50055
         METRICS_PORT_PAYMENT: 9105
         ORDER_GRPC_ADDR: order-service:50053
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50055:50055"
         - "9105:9105"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         order-service:
            condition: service_started
      restart: always

   # Shipping Service
   shipping-service:
      build:
         context: .
         dockerfile: ./cmd/shipping-service/Dockerfile
      container_name: ecommerce_shipping_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_SHIPPING: 50056
         METRICS_PORT_SHIPPING: 9106
         ORDER_GRPC_ADDR: order-service:50053
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50056:50056"
         - "9106:9106"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         order-service:
            condition: service_started
      restart: always

   # Auth Service
   auth-service:
      build:
         context: .
         dockerfile: ./cmd/auth-service/Dockerfile
      container_name: ecommerce_auth_service
      environment:
         REDIS_ADDR: redis:6379
         GRPC_PORT_AUTH: 50057
         METRICS_PORT_AUTH: 9107
         USER_GRPC_ADDR: user-service:50051
         JWT_SECRET: your_very_secure_and_long_jwt_secret_key_here_change_this_in_production
         ACCESS_TOKEN_TTL: 15m
         REFRESH_TOKEN_TTL: 7d
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50057:50057"
         - "9107:9107"
      depends_on:
         user-service:
            condition: service_started
      restart: always

   # Notification Service
   notification-service:
      build:
         context: .
         dockerfile: ./cmd/notification-service/Dockerfile
      container_name: ecommerce_notification_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_NOTIFICATION: 50058
         METRICS_PORT_NOTIFICATION: 9108
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50058:50058"
         - "9108:9108"
      depends_on:
         migration-service:
            condition: service_completed_successfully
      restart: always

   # Inventory Service
   inventory-service:
      build:
         context: .
         dockerfile: ./cmd/inventory-service/Dockerfile
      container_name: ecommerce_inventory_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_INVENTORY: 50059
         METRICS_PORT_INVENTORY: 9109
         KAFKA_BROKER_ADDR: kafka:9092
         KAFKA_PRODUCT_EVENTS_TOPIC: product_events
         KAFKA_INVENTORY_CONSUMER_GROUP_ID: inventory-service-group
         PRODUCT_GRPC_ADDR: product-service:50052
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50059:50059"
         - "9109:9109"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         product-service:
            condition: service_started
      restart: always

   # Review Service
   review-service:
      build:
         context: .
         dockerfile: ./cmd/review-service/Dockerfile
      container_name: ecommerce_review_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_REVIEW: 50060
         METRICS_PORT_REVIEW: 9110
         PRODUCT_GRPC_ADDR: product-service:50052
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50060:50060"
         - "9110:9110"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         product-service:
            condition: service_started
      restart: always

   # Search Service
   search-service:
      build:
         context: .
         dockerfile: ./cmd/search-service/Dockerfile
      container_name: ecommerce_search_service
      environment:
         ELASTICSEARCH_ADDR: http://elasticsearch:9200
         GRPC_PORT_SEARCH: 50061
         METRICS_PORT_SEARCH: 9111
         KAFKA_BROKER_ADDR: kafka:9092
         KAFKA_PRODUCT_EVENTS_TOPIC: product_events
         KAFKA_SEARCH_CONSUMER_GROUP_ID: search-service-group
         PRODUCT_GRPC_ADDR: product-service:50052
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50061:50061"
         - "9111:9111"
      depends_on:
         product-service:
            condition: service_started
      restart: always

   # Recommendation Service
   recommendation-service:
      build:
         context: .
         dockerfile: ./cmd/recommendation-service/Dockerfile
      container_name: ecommerce_recommendation_service
      environment:
         DATABASE_URL: postgres://user:password@core_db:5432/ecommerce_core_db?sslmode=disable
         GRPC_PORT_RECOMMENDATION: 50062
         METRICS_PORT_RECOMMENDATION: 9112
         PRODUCT_GRPC_ADDR: product-service:50052
         KAFKA_BROKER_ADDR: kafka:9092
         KAFKA_PRODUCT_EVENTS_TOPIC: product_events
         KAFKA_RECOMMENDATION_CONSUMER_GROUP_ID: recommendation-service-group
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "50062:50062"
         - "9112:9112"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         product-service:
            condition: service_started
      restart: always

   # API Gateway (using Dockerfile)
   api-gateway:
      build:
         context: .
         dockerfile: ./cmd/api-gateway/Dockerfile
      container_name: ecommerce_api_gateway
      environment:
         HTTP_PORT: 8080
         METRICS_PORT_API_GATEWAY: 9080
         USER_GRPC_ADDR: user-service:50051
         PRODUCT_GRPC_ADDR: product-service:50052
         ORDER_GRPC_ADDR: order-service:50053
         CART_GRPC_ADDR: cart-service:50054
         PAYMENT_GRPC_ADDR: payment-service:50055
         SHIPPING_GRPC_ADDR: shipping-service:50056
         AUTH_GRPC_ADDR: auth-service:50057
         NOTIFICATION_GRPC_ADDR: notification-service:50058
         INVENTORY_GRPC_ADDR: inventory-service:50059
         REVIEW_GRPC_ADDR: review-service:50060
         SEARCH_GRPC_ADDR: search-service:50061
         RECOMMENDATION_GRPC_ADDR: recommendation-service:50062
         JWT_SECRET: your_very_secure_and_long_jwt_secret_key_here_change_this_in_production
         ACCESS_TOKEN_TTL: 15m
         REFRESH_TOKEN_TTL: 7d
         JAEGER_COLLECTOR_URL: http://jaeger:14268/api/traces
         LOG_LEVEL: INFO
      ports:
         - "8080:8080"
         - "9080:9080"
      depends_on:
         migration-service:
            condition: service_completed_successfully
         user-service:
            condition: service_started
         product-service:
            condition: service_started
         order-service:
            condition: service_started
         cart-service:
            condition: service_started
         payment-service:
            condition: service_started
         shipping-service:
            condition: service_started
         auth-service:
            condition: service_started
         notification-service:
            condition: service_started
         inventory-service:
            condition: service_started
         review-service:
            condition: service_started
         search-service:
            condition: service_started
         recommendation-service:
            condition: service_started
      restart: always
