# ⚙️ Không cần version nữa (Docker cảnh báo version đã obsolete)
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ecommerce-prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    volumes:
      - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infrastructure/monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - ecommerce-network
    depends_on:
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    container_name: ecommerce-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ecommerce-alertmanager
    restart: unless-stopped
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - ./infrastructure/monitoring/prometheus/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - ecommerce-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ecommerce-node-exporter
    restart: unless-stopped
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - ecommerce-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: ecommerce-postgres-exporter
    restart: unless-stopped
    environment:
      # ⚠️ Giữ nguyên kết nối tới Postgres ở compose chính
      DATA_SOURCE_NAME: "postgresql://postgres:postgres123@ecommerce-postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - ecommerce-network
    # ⚠️ ĐÃ BỎ depends_on vì postgres nằm ở file compose khác

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ecommerce-jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector HTTP
      - "14250:14250" # Jaeger collector gRPC
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - ecommerce-network

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  ecommerce-network:
    external: true
    name: ecommerce-go-app_ecommerce-network
