global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ecommerce-production'
    environment: 'prod'

rule_files:
  - '/etc/prometheus/alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8000']
        labels:
          service: 'api-gateway'

  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:8001']
        labels:
          service: 'user-service'

  - job_name: 'product-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['product-service:8002']
        labels:
          service: 'product-service'

  - job_name: 'order-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['order-service:8003']
        labels:
          service: 'order-service'

  - job_name: 'notification-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notification-service:8004']
        labels:
          service: 'notification-service'

  - job_name: 'inventory-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['inventory-service:8005']
        labels:
          service: 'inventory-service'

  - job_name: 'payment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['payment-service:8006']
        labels:
          service: 'payment-service'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
