// api/protobufs/search.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: search.proto

package search_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_IndexProduct_FullMethodName           = "/search.SearchService/IndexProduct"
	SearchService_SearchProducts_FullMethodName         = "/search.SearchService/SearchProducts"
	SearchService_DeleteProductFromIndex_FullMethodName = "/search.SearchService/DeleteProductFromIndex"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SearchService defines the gRPC service for product search.
// SearchService định nghĩa dịch vụ gRPC cho tìm kiếm sản phẩm.
type SearchServiceClient interface {
	// RPC to index a product (add/update it in the search engine)
	// RPC để lập chỉ mục sản phẩm (thêm/cập nhật vào công cụ tìm kiếm)
	IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error)
	// RPC to search for products based on keywords and filters
	// RPC để tìm kiếm sản phẩm dựa trên từ khóa và bộ lọc
	SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
	// RPC to delete a product from the search index
	// RPC để xóa một sản phẩm khỏi chỉ mục tìm kiếm
	DeleteProductFromIndex(ctx context.Context, in *DeleteProductFromIndexRequest, opts ...grpc.CallOption) (*DeleteProductFromIndexResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexProductResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteProductFromIndex(ctx context.Context, in *DeleteProductFromIndexRequest, opts ...grpc.CallOption) (*DeleteProductFromIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductFromIndexResponse)
	err := c.cc.Invoke(ctx, SearchService_DeleteProductFromIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
//
// SearchService defines the gRPC service for product search.
// SearchService định nghĩa dịch vụ gRPC cho tìm kiếm sản phẩm.
type SearchServiceServer interface {
	// RPC to index a product (add/update it in the search engine)
	// RPC để lập chỉ mục sản phẩm (thêm/cập nhật vào công cụ tìm kiếm)
	IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error)
	// RPC to search for products based on keywords and filters
	// RPC để tìm kiếm sản phẩm dựa trên từ khóa và bộ lọc
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	// RPC to delete a product from the search index
	// RPC để xóa một sản phẩm khỏi chỉ mục tìm kiếm
	DeleteProductFromIndex(context.Context, *DeleteProductFromIndexRequest) (*DeleteProductFromIndexResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexProduct not implemented")
}
func (UnimplementedSearchServiceServer) SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedSearchServiceServer) DeleteProductFromIndex(context.Context, *DeleteProductFromIndexRequest) (*DeleteProductFromIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductFromIndex not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_IndexProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexProduct(ctx, req.(*IndexProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteProductFromIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductFromIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteProductFromIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteProductFromIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteProductFromIndex(ctx, req.(*DeleteProductFromIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexProduct",
			Handler:    _SearchService_IndexProduct_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _SearchService_SearchProducts_Handler,
		},
		{
			MethodName: "DeleteProductFromIndex",
			Handler:    _SearchService_DeleteProductFromIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
