// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: recommendation.proto

package recommendation_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message representing a product in recommendations
type RecommendedProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // Main image URL for display
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                     // Recommendation score/relevance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedProduct) Reset() {
	*x = RecommendedProduct{}
	mi := &file_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedProduct) ProtoMessage() {}

func (x *RecommendedProduct) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedProduct.ProtoReflect.Descriptor instead.
func (*RecommendedProduct) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendedProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RecommendedProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommendedProduct) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RecommendedProduct) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Request for recording a user interaction
type RecordInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "view", "add_to_cart", "purchase"
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInteractionRequest) Reset() {
	*x = RecordInteractionRequest{}
	mi := &file_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInteractionRequest) ProtoMessage() {}

func (x *RecordInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInteractionRequest.ProtoReflect.Descriptor instead.
func (*RecordInteractionRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecordInteractionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordInteractionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RecordInteractionRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordInteractionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Response for recording a user interaction
type RecordInteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInteractionResponse) Reset() {
	*x = RecordInteractionResponse{}
	mi := &file_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInteractionResponse) ProtoMessage() {}

func (x *RecordInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInteractionResponse.ProtoReflect.Descriptor instead.
func (*RecordInteractionResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecordInteractionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordInteractionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for getting product recommendations for a user
type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Max number of recommendations to return
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Offset for pagination (if needed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRecommendationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response for getting product recommendations
type GetRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*RecommendedProduct  `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendationsResponse) GetProducts() []*RecommendedProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetRecommendationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for getting top N popular products
type GetPopularProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Max number of popular products to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularProductsRequest) Reset() {
	*x = GetPopularProductsRequest{}
	mi := &file_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularProductsRequest) ProtoMessage() {}

func (x *GetPopularProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularProductsRequest.ProtoReflect.Descriptor instead.
func (*GetPopularProductsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *GetPopularProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response for getting top N popular products
type GetPopularProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*RecommendedProduct  `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularProductsResponse) Reset() {
	*x = GetPopularProductsResponse{}
	mi := &file_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularProductsResponse) ProtoMessage() {}

func (x *GetPopularProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularProductsResponse.ProtoReflect.Descriptor instead.
func (*GetPopularProductsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *GetPopularProductsResponse) GetProducts() []*RecommendedProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetPopularProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x14recommendation.proto\"z\n" +
	"\x12RecommendedProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"\x8f\x01\n" +
	"\x18RecordInteractionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"O\n" +
	"\x19RecordInteractionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"g\n" +
	"\x1aGetRecommendationsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.RecommendedProductR\bproducts\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x19GetPopularProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"g\n" +
	"\x1aGetPopularProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.RecommendedProductR\bproducts\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x81\x02\n" +
	"\x15RecommendationService\x12J\n" +
	"\x11RecordInteraction\x12\x19.RecordInteractionRequest\x1a\x1a.RecordInteractionResponse\x12M\n" +
	"\x12GetRecommendations\x12\x1a.GetRecommendationsRequest\x1a\x1b.GetRecommendationsResponse\x12M\n" +
	"\x12GetPopularProducts\x12\x1a.GetPopularProductsRequest\x1a\x1b.GetPopularProductsResponseBWZUgithub.com/datngth03/ecommerce-go-app/pkg/client/recommendation;recommendation_clientb\x06proto3"

var (
	file_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_proto_rawDescData []byte
)

func file_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)))
	})
	return file_recommendation_proto_rawDescData
}

var file_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_recommendation_proto_goTypes = []any{
	(*RecommendedProduct)(nil),         // 0: RecommendedProduct
	(*RecordInteractionRequest)(nil),   // 1: RecordInteractionRequest
	(*RecordInteractionResponse)(nil),  // 2: RecordInteractionResponse
	(*GetRecommendationsRequest)(nil),  // 3: GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil), // 4: GetRecommendationsResponse
	(*GetPopularProductsRequest)(nil),  // 5: GetPopularProductsRequest
	(*GetPopularProductsResponse)(nil), // 6: GetPopularProductsResponse
}
var file_recommendation_proto_depIdxs = []int32{
	0, // 0: GetRecommendationsResponse.products:type_name -> RecommendedProduct
	0, // 1: GetPopularProductsResponse.products:type_name -> RecommendedProduct
	1, // 2: RecommendationService.RecordInteraction:input_type -> RecordInteractionRequest
	3, // 3: RecommendationService.GetRecommendations:input_type -> GetRecommendationsRequest
	5, // 4: RecommendationService.GetPopularProducts:input_type -> GetPopularProductsRequest
	2, // 5: RecommendationService.RecordInteraction:output_type -> RecordInteractionResponse
	4, // 6: RecommendationService.GetRecommendations:output_type -> GetRecommendationsResponse
	6, // 7: RecommendationService.GetPopularProducts:output_type -> GetPopularProductsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommendation_proto_init() }
func file_recommendation_proto_init() {
	if File_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_proto = out.File
	file_recommendation_proto_goTypes = nil
	file_recommendation_proto_depIdxs = nil
}
