# docker/prometheus/prometheus.yml
global:
  scrape_interval: 15s # Thu thập metrics mỗi 15 giây
  evaluation_interval: 15s # Đánh giá các quy tắc cảnh báo mỗi 15 giây

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Tự giám sát Prometheus

  - job_name: 'go_microservices' # Giám sát các microservice Go của bạn
    static_configs:
      - targets:
          - 'host.docker.internal:9101'
          - 'host.docker.internal:9102'
          - 'host.docker.internal:9103'
          - 'host.docker.internal:9104'
          - 'host.docker.internal:9105'
          - 'host.docker.internal:9106'
          - 'host.docker.internal:9107'
          - 'host.docker.internal:9108'
          - 'host.docker.internal:9109'
          - 'host.docker.internal:9110'
          - 'host.docker.internal:9111'
          - 'host.docker.internal:9112'
          - 'host.docker.internal:9080'
    metrics_path: /metrics

    