# .github/workflows/build-and-test.yml
name: Go Build and Test

on:
  push:
    branches:
      - main # Chạy workflow khi có push lên nhánh main
      - develop # Hoặc nhánh phát triển của bạn
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Chạy trên môi trường Ubuntu mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Lấy mã nguồn từ repository

      - name: Set up Go
        uses: actions/setup-go@v5 # Thiết lập môi trường Go
        with:
          go-version: '1.22' # Sử dụng phiên bản Go 1.22 (hoặc phiên bản bạn đang dùng)

      - name: Install Go dependencies
        run: go mod tidy # Tải các dependencies của Go modules

      - name: Generate Protobufs
        run: chmod +x ./scripts/generate_protos.sh && ./scripts/generate_protos.sh # Chạy script để tạo lại mã Protobuf
        # Đảm bảo script này có thể chạy trong môi trường CI (có thể cần cài đặt protoc nếu không có sẵn)

      - name: Build all Microservices
        run: |
          echo "Building User Service..."
          go build -o ./bin/user-service ./cmd/user-service/main.go
          echo "Building Product Service..."
          go build -o ./bin/product-service ./cmd/product-service/main.go
          echo "Building Order Service..."
          go build -o ./bin/order-service ./cmd/order-service/main.go
          echo "Building Cart Service..."
          go build -o ./bin/cart-service ./cmd/cart-service/main.go
          echo "Building Payment Service..."
          go build -o ./bin/payment-service ./cmd/payment-service/main.go
          echo "Building Shipping Service..."
          go build -o ./bin/shipping-service ./cmd/shipping-service/main.go
          echo "Building Auth Service..."
          go build -o ./bin/auth-service ./cmd/auth-service/main.go
          echo "Building Notification Service..."
          go build -o ./bin/notification-service ./cmd/notification-service/main.go
          echo "Building Inventory Service..."
          go build -o ./bin/inventory-service ./cmd/inventory-service/main.go
          echo "Building Review Service..."
          go build -o ./bin/review-service ./cmd/review-service/main.go
          echo "Building Search Service..."
          go build -o ./bin/search-service ./cmd/search-service/main.go
          echo "Building Recommendation Service..."
          go build -o ./bin/recommendation-service ./cmd/recommendation-service/main.go
          echo "Building API Gateway..."
          go build -o ./bin/api-gateway ./cmd/api-gateway/main.go
        # Tạo thư mục bin nếu chưa có
        working-directory: .
        env:
          CGO_ENABLED: 0 # Tắt CGO để tạo binary tĩnh, dễ dàng di chuyển

      - name: Run Unit Tests
        run: go test -v ./... # Chạy tất cả các unit tests trong dự án
        # Đảm bảo các unit tests của bạn không yêu cầu kết nối DB/Redis/Kafka thực
        # hoặc sử dụng mock/stub cho các kết nối đó.

      - name: Upload Binaries (Optional)
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: go-binaries
          path: ./bin/ # Tải lên các binary đã build
