name: Deploy to Production

on:
   release:
      types: [published]

jobs:
   deploy-production:
      runs-on: ubuntu-latest
      environment: production
      steps:
         - uses: actions/checkout@v3

         - name: Install kubectl
           uses: azure/setup-kubectl@v3

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v2
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-southeast-1

         - name: Update kubeconfig
           run: aws eks update-kubeconfig --name production-cluster

         - name: Deploy to EKS
           run: |
              kubectl apply -f k8s/production/
              kubectl rollout restart deployment -n ecommerce
