name: Continuous Integration

on:
   push:
      branches: [main, develop]
   pull_request:
      branches: [main, develop]

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Set up Go
           uses: actions/setup-go@v4
           with:
              go-version: "1.21"

         - name: Install dependencies
           run: go mod download

         - name: Run tests
           run: go test ./... -v -race -cover

         - name: Run linter
           uses: golangci/golangci-lint-action@v3

   build:
      needs: test
      runs-on: ubuntu-latest
      strategy:
         matrix:
            service:
               [
                  api-gateway,
                  user-service,
                  product-service,
                  order-service,
                  cart-service,
                  payment-service,
                  shipping-service,
                  auth-service,
                  notification-service,
                  inventory-service,
                  review-service,
                  search-service,
                  recommendation-service,
               ]
      steps:
         - uses: actions/checkout@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Build and push Docker image
           uses: docker/build-push-action@v4
           with:
              context: .
              file: ./cmd/${{ matrix.service }}/Dockerfile
              push: true
              tags: |
                 ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
                 ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
